### ISSUE TITLE
(!) Реализовать выданные интерфейсы

### ISSUE THREAD

**Issue by avasyukov** [mrsmellstone/Brownian-motion#1]
В условиях задачи было требование реализовать выданные интерфейсы. Это нужно сделать. Без этого проверка по сути задачи не имеет смысла.

**Comment by avasyukov** [comment]
По коду - стало, конечно, теплее и правдоподобнее. Но интерфейсы-то где? Есть два пустых хэдера. Этого, однако, мало.

**Comment by avasyukov** [comment]
Теперь в хэдерах есть объявление интерфейсов. Ок. Стало ещё теплее. А реализация-то где? Её по-прежнему в коде не обнаружено.

**Comment by mrsmellstone** [comment]
Все это время в main существовал не тот код:(
Сейчас закинула нужный. Будет ли это уже учитываться, не знаю. Срок-то, к сожалению, прошел.

**Comment by avasyukov** [comment]
Ещё теплее.

Сейчас всё хорошо в рамках *вашего* main.

Но интерфейс предполагает, что doTimeStep переводит сцену в следующее состояние *полностью*. Сейчас для целостного перехода нужно doTimeStep + серия correct_\*. Проблема в том, что *внешний* код (в данном случае для примера визуализатор) ничего не знает о наличии методов correct_\* и не вызовет их. Так что все необходимые действия должны быть завершены после завершения doTimeStep.

Иметь в своём отладочном main-е разные дополнительные действия - полностью ок. Внешний код это не вызовет. Но ему и не надо. А вот целостное новое состояние сцены после только doTimeStep внешний код получить должен.

**Comment by mrsmellstone** [comment]
Исправила.

**Comment by avasyukov** [comment]
Реализовано. Дальше обсудим уже завтра.
